<?php if(!class_exists('Rain\Tpl')){exit;}?>    <div class="caixa">
        <div class="linha">
            <div class="c c12">
                <h2 class="titulo2">DÚVIDAS NA INSTALAÇÃO</h2>
                <p class="p justificar">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus arcu, euismod venenatis venenatis quis, congue a orci. Pellentesque ac cursus lacus, et vulputate dolor. Mauris fermentum risus erat. Nunc sed tellus et eros suscipit mollis sed sed sapien. Sed sit amet ipsum quis leo congue dapibus at eu nunc. Aliquam dui elit, sodales ac ultricies vitae, sagittis non mauris. Aliquam ultricies nunc auctor lobortis volutpat. In varius nulla urna, gravida rhoncus enim egestas at. Donec vel odio quis odio gravida maximus.

                    Maecenas metus ante, placerat ac nisi eu, dignissim pellentesque lectus. Aliquam venenatis ipsum luctus metus gravida posuere. Donec id pulvinar risus. Integer faucibus imperdiet augue, scelerisque suscipit felis aliquam eu. Vestibulum eu sapien vitae nisi lobortis hendrerit vitae nec nulla. Cras facilisis varius luctus. Nunc interdum blandit metus ut rutrum. Curabitur tincidunt purus et mauris porttitor feugiat. Ut volutpat efficitur mi, et iaculis massa tristique et. Integer hendrerit ut tortor in consectetur. In in viverra neque. Proin mollis interdum tortor at dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                </p>
                <br>
                <h2 class="titulo2">PRICIPAIS FUNÇÕES DA CUP</h2>
                <p class="p justificar">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus arcu, euismod venenatis venenatis quis, congue a orci. Pellentesque ac cursus lacus, et vulputate dolor. Mauris fermentum risus erat. Nunc sed tellus et eros suscipit mollis sed sed sapien. Sed sit amet ipsum quis leo congue dapibus at eu nunc. Aliquam dui elit, sodales ac ultricies vitae, sagittis non mauris. Aliquam ultricies nunc auctor lobortis volutpat. In varius nulla urna, gravida rhoncus enim egestas at. Donec vel odio quis odio gravida maximus.

                    Maecenas metus ante, placerat ac nisi eu, dignissim pellentesque lectus. Aliquam venenatis ipsum luctus metus gravida posuere. Donec id pulvinar risus. Integer faucibus imperdiet augue, scelerisque suscipit felis aliquam eu. Vestibulum eu sapien vitae nisi lobortis hendrerit vitae nec nulla. Cras facilisis varius luctus. Nunc interdum blandit metus ut rutrum. Curabitur tincidunt purus et mauris porttitor feugiat. Ut volutpat efficitur mi, et iaculis massa tristique et. Integer hendrerit ut tortor in consectetur. In in viverra neque. Proin mollis interdum tortor at dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus arcu, euismod venenatis venenatis quis, congue a orci. Pellentesque ac cursus lacus, et vulputate dolor. Mauris fermentum risus erat. Nunc sed tellus et eros suscipit mollis sed sed sapien. Sed sit amet ipsum quis leo congue dapibus at eu nunc. Aliquam dui elit, sodales ac ultricies vitae, sagittis non mauris. Aliquam ultricies nunc auctor lobortis volutpat. In varius nulla urna, gravida rhoncus enim egestas at. Donec vel odio quis odio gravida maximus.

                    Maecenas metus ante, placerat ac nisi eu, dignissim pellentesque lectus. Aliquam venenatis ipsum luctus metus gravida posuere. Donec id pulvinar risus. Integer faucibus imperdiet augue, scelerisque suscipit felis aliquam eu. Vestibulum eu sapien vitae nisi lobortis hendrerit vitae nec nulla. Cras facilisis varius luctus. Nunc interdum blandit metus ut rutrum. Curabitur tincidunt purus et mauris porttitor feugiat. Ut volutpat efficitur mi, et iaculis massa tristique et. Integer hendrerit ut tortor in consectetur. In in viverra neque. Proin mollis interdum tortor at dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                </p>
                <br>
                <h2 class="titulo2">PLUGINS ADICIONAIS</h2>
                <p class="p justificar">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus arcu, euismod venenatis venenatis quis, congue a orci. Pellentesque ac cursus lacus, et vulputate dolor. Mauris fermentum risus erat. Nunc sed tellus et eros suscipit mollis sed sed sapien. Sed sit amet ipsum quis leo congue dapibus at eu nunc. Aliquam dui elit, sodales ac ultricies vitae, sagittis non mauris. Aliquam ultricies nunc auctor lobortis volutpat. In varius nulla urna, gravida rhoncus enim egestas at. Donec vel odio quis odio gravida maximus.

                    Maecenas metus ante, placerat ac nisi eu, dignissim pellentesque lectus. Aliquam venenatis ipsum luctus metus gravida posuere. Donec id pulvinar risus. Integer faucibus imperdiet augue, scelerisque suscipit felis aliquam eu. Vestibulum eu sapien vitae nisi lobortis hendrerit vitae nec nulla. Cras facilisis varius luctus. Nunc interdum blandit metus ut rutrum. Curabitur tincidunt purus et mauris porttitor feugiat. Ut volutpat efficitur mi, et iaculis massa tristique et. Integer hendrerit ut tortor in consectetur. In in viverra neque. Proin mollis interdum tortor at dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus arcu, euismod venenatis venenatis quis, congue a orci. Pellentesque ac cursus lacus, et vulputate dolor. Mauris fermentum risus erat. Nunc sed tellus et eros suscipit mollis sed sed sapien. Sed sit amet ipsum quis leo congue dapibus at eu nunc. Aliquam dui elit, sodales ac ultricies vitae, sagittis non mauris. Aliquam ultricies nunc auctor lobortis volutpat. In varius nulla urna, gravida rhoncus enim egestas at. Donec vel odio quis odio gravida maximus.

                    Maecenas metus ante, placerat ac nisi eu, dignissim pellentesque lectus. Aliquam venenatis ipsum luctus metus gravida posuere. Donec id pulvinar risus. Integer faucibus imperdiet augue, scelerisque suscipit felis aliquam eu. Vestibulum eu sapien vitae nisi lobortis hendrerit vitae nec nulla. Cras facilisis varius luctus. Nunc interdum blandit metus ut rutrum. Curabitur tincidunt purus et mauris porttitor feugiat. Ut volutpat efficitur mi, et iaculis massa tristique et. Integer hendrerit ut tortor in consectetur. In in viverra neque. Proin mollis interdum tortor at dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec metus arcu, euismod venenatis venenatis quis, congue a orci. Pellentesque ac cursus lacus, et vulputate dolor. Mauris fermentum risus erat. Nunc sed tellus et eros suscipit mollis sed sed sapien. Sed sit amet ipsum quis leo congue dapibus at eu nunc. Aliquam dui elit, sodales ac ultricies vitae, sagittis non mauris. Aliquam ultricies nunc auctor lobortis volutpat. In varius nulla urna, gravida rhoncus enim egestas at. Donec vel odio quis odio gravida maximus.

                    Maecenas metus ante, placerat ac nisi eu, dignissim pellentesque lectus. Aliquam venenatis ipsum luctus metus gravida posuere. Donec id pulvinar risus. Integer faucibus imperdiet augue, scelerisque suscipit felis aliquam eu. Vestibulum eu sapien vitae nisi lobortis hendrerit vitae nec nulla. Cras facilisis varius luctus. Nunc interdum blandit metus ut rutrum. Curabitur tincidunt purus et mauris porttitor feugiat. Ut volutpat efficitur mi, et iaculis massa tristique et. Integer hendrerit ut tortor in consectetur. In in viverra neque. Proin mollis interdum tortor at dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                </p>
                <br><br>
                <p class="p centralizar">
                    <button class="b b-padrao">BAIXAR DOCUMENTAÇÃO COMPLETA</button>
                </p>
            </div>
        </div>
    </div>