<?php if(!class_exists('Rain\Tpl')){exit;}?>    <div class="caixa">
        <div class="linha">
            <div class="c c12 justificar">
                <h2 class="titulo2">TERMOS DE USO</h2>
                <p class="p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in lectus lobortis, sagittis felis sed, interdum est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed vel consequat lacus. Proin lobortis consequat mauris, vitae sagittis lectus iaculis ac. Aenean lacinia tincidunt lacus scelerisque mattis. Curabitur ullamcorper rhoncus nisi, sed iaculis metus vehicula eget. Nam a interdum lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed felis arcu, imperdiet vel pretium ut, luctus convallis orci. Etiam mattis erat nulla, sed faucibus massa euismod sed. Aenean a odio sit amet sem hendrerit lacinia at at ante. Vestibulum elit nulla, ultricies ut molestie sed, sollicitudin laoreet libero. Phasellus lobortis nunc ut sem scelerisque sodales. Nulla vehicula accumsan orci vitae consequat.</p>
                <p class="p">Aenean molestie at dolor at auctor. Curabitur dignissim dolor vel erat luctus condimentum. Nullam vitae dui eget nisi euismod hendrerit a id justo. Nam nec risus tellus. Mauris eu efficitur tortor. Aenean fermentum ipsum sapien, vel dignissim metus feugiat vel. Nulla vel pretium nisl. Vestibulum quam augue, elementum et faucibus eu, commodo nec diam. Phasellus at lectus massa.</p>
                <h2 class="titulo2">CONDUTA DO VISITANTE</h2>
                <ul class="p">
                    <li>Nulla vel pretium nisl. Vestibulum quam augue, elementum et faucibus eu, commodo nec diam. Phasellus at lectus massa.</li>
                    <li>Nam nec risus quis mi luctus ultricies. Aliquam posuere ultricies ultrices. Nam ornare lectus condimentum nisl pulvinar varius non a quam. Duis non tristique erat. Curabitur ullamcorper posuere semper.</li>
                    <li>Suspendisse efficitur condimentum augue, ac varius diam mattis vel. Duis et porttitor nunc. In hac habitasse platea dictumst. Donec mi eros, pharetra ut consequat at, euismod et leo.</li>
                    <li>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</li>
                </ul>
                </div>
                <h2 class="titulo2">ACESSO INTERNACIONAL</h2>
                <p class="p">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus eu bibendum erat. Sed aliquet rutrum ex eu lobortis. Duis magna nulla, ultricies at aliquet non, interdum id mi. Sed et consectetur tortor, a tincidunt lacus. Sed eu cursus orci. Donec pretium augue ac massa dapibus, quis ullamcorper felis eleifend. Suspendisse aliquam massa nec magna viverra porttitor. Duis imperdiet fringilla finibus. Vivamus a ornare tortor. Etiam id cursus sem, id cursus sem. Nam nec risus quis mi luctus ultricies. Aliquam posuere ultricies ultrices. Nam ornare lectus condimentum nisl pulvinar varius non a quam. Duis non tristique erat. Curabitur ullamcorper posuere semper.</p>
                <h2 class="titulo2">INFORMAÇÃO DE PRIVACIDADE</h2>
                <p class="p">Nullam ac risus metus. Aenean vitae nunc pharetra, placerat lacus convallis, fringilla augue. Integer ut neque leo. Curabitur rutrum molestie consectetur. Mauris consectetur, ipsum vel feugiat placerat, mi nibh feugiat ex, efficitur ullamcorper ipsum metus fermentum enim. In hac habitasse platea dictumst. Morbi tempor, nisl a imperdiet dignissim, orci urna luctus massa, vitae dignissim urna sapien ut mi. Curabitur pulvinar quam in arcu facilisis eleifend. Phasellus ut ante vitae nulla vulputate vehicula eget ac ligula. Nulla rutrum in lectus nec egestas. Pellentesque egestas, enim eget porttitor hendrerit, sapien risus ullamcorper velit, ut finibus tellus libero eu ex. Suspendisse efficitur condimentum augue, ac varius diam mattis vel. Duis et porttitor nunc. In hac habitasse platea dictumst. Donec mi eros, pharetra ut consequat at, euismod et leo.</p>
                <p class="p">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis mattis neque et neque volutpat, non egestas diam accumsan. Pellentesque mattis eros non semper commodo. Vestibulum auctor nisi a dapibus facilisis. Nunc eget euismod nunc. Proin nisi nibh, pharetra nec leo non, finibus vulputate leo.</p>
                <h2 class="titulo2">USO DE CONTEÚDO DO SITE</h2>
                <div class="p">
                    <ul>
                        <li>Nulla vel pretium nisl. Vestibulum quam augue, elementum et faucibus eu, commodo nec diam. Phasellus at lectus massa.</li>
                        <li>Nam nec risus quis mi luctus ultricies. Aliquam posuere ultricies ultrices. Nam ornare lectus condimentum nisl pulvinar varius non a quam. Duis non tristique erat. Curabitur ullamcorper posuere semper.</li>
                        <li>Suspendisse efficitur condimentum augue, ac varius diam mattis vel. Duis et porttitor nunc. In hac habitasse platea dictumst. Donec mi eros, pharetra ut consequat at, euismod et leo.</li>
                        <li>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</li>
                        <li>Nam ornare lectus condimentum nisl pulvinar varius non a quam. Duis non tristique erat. Curabitur ullamcorper posuere semper.</li>
                        <li>Duis et porttitor nunc. In hac habitasse platea dictumst. Donec mi eros, pharetra ut consequat at, euismod et leo.</li>
                    </ul>
                </div>
                <h2 class="titulo2">DIREITOS E LICENÇAS DE PROPRIEDADE INTELECTUAL</h2>
                <p class="p">Nullam ac risus metus. Aenean vitae nunc pharetra, placerat lacus convallis, fringilla augue. Integer ut neque leo. Curabitur rutrum molestie consectetur. Mauris consectetur, ipsum vel feugiat placerat, mi nibh feugiat ex, efficitur ullamcorper ipsum metus fermentum enim. In hac habitasse platea dictumst. Morbi tempor, nisl a imperdiet dignissim, orci urna luctus massa, vitae dignissim urna sapien ut mi. Curabitur pulvinar quam in arcu facilisis eleifend. Phasellus ut ante vitae nulla vulputate vehicula eget ac ligula. Nulla rutrum in lectus nec egestas. Pellentesque egestas, enim eget porttitor hendrerit, sapien risus ullamcorper velit, ut finibus tellus libero eu ex. Suspendisse efficitur condimentum augue, ac varius diam mattis vel. Duis et porttitor nunc. In hac habitasse platea dictumst. Donec mi eros, pharetra ut consequat at, euismod et leo.</p>
                <h2 class="titulo2">USO DE SOFTWARE</h2>
                <p class="p">Nullam ac risus metus. Aenean vitae nunc pharetra, placerat lacus convallis, fringilla augue. Integer ut neque leo. Curabitur rutrum molestie consectetur. Mauris consectetur, ipsum vel feugiat placerat, mi nibh feugiat ex, efficitur ullamcorper ipsum metus fermentum enim. In hac habitasse platea dictumst. Morbi tempor, nisl a imperdiet dignissim, orci urna luctus massa, vitae dignissim urna sapien ut mi. Curabitur pulvinar quam in arcu facilisis eleifend. Phasellus ut ante vitae nulla vulputate vehicula eget ac ligula. Nulla rutrum in lectus nec egestas. Pellentesque egestas, enim eget porttitor hendrerit, sapien risus ullamcorper velit, ut finibus tellus libero eu ex. Suspendisse efficitur condimentum augue, ac varius diam mattis vel. Duis et porttitor nunc. In hac habitasse platea dictumst. Donec mi eros, pharetra ut consequat at, euismod et leo.</p>
                <p class="p">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis mattis neque et neque volutpat, non egestas diam accumsan. Pellentesque mattis eros non semper commodo. Vestibulum auctor nisi a dapibus facilisis. Nunc eget euismod nunc. Proin nisi nibh, pharetra nec leo non, finibus vulputate leo.</p>
                <h2 class="titulo2">USO DE MARCAS REGISTRADAS</h2>
                <p class="p">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis mattis neque et neque volutpat, non egestas diam accumsan. Pellentesque mattis eros non semper commodo. Vestibulum auctor nisi a dapibus facilisis. Nunc eget euismod nunc. Proin nisi nibh, pharetra nec leo non, finibus vulputate leo.</p>
            </div>
        </div>
    </div>